### ISSUE TITLE
Found a lot of endpoints to crash the entire app

### ISSUE THREAD

**Issue by CR072** [heliactyloss/heliactyl#7]
There are dozens of endpoints which will crash the entire app. In some endpoints you just have to visit it, no need to enter any query or params. Thanks to a few summer hosts for using Heliactyl 14 (I was able to test it really fast).

**Comment by Nightmaregodss** [comment]
Same here

**Comment by zebronixllc** [comment]
it was my host ( reyo )

**Comment by CR072** [comment]
> it was my host ( reyo )

A few other summer hosts helped too, btw I appreciate your publicity.

**Comment by atqr1** [comment]
> There are dozens of endpoints which will crash the entire app. In some endpoints you just have to visit it, no need to enter any query or params. Thanks to a few summer hosts for using Heliactyl 14 (I was able to test it really fast).

this is what happens when 2 years of my random changes end up in public heliactyl

**Comment by atqr1** [comment]
kindly send them here or DM me then

**Comment by atqr1** [comment]
i just quickly pushed this out - it wasn't meant to be a public release so I'm not surprised by this

**Comment by amperext** [comment]
This clearly isn't relevant anymore
